---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - demo.mega.crd
  resources:
  - hellos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.mega.crd
  resources:
  - hellos/finalizers
  verbs:
  - update
- apiGroups:
  - demo.mega.crd
  resources:
  - hellos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: [ "get", "list", "watch" ]