apiVersion: demo.mega.crd/v1
kind: Hello
metadata:
  labels:
    app.kubernetes.io/name: hello
    app.kubernetes.io/instance: hello-sample
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator
  name: hello-sample
spec:
  # TODO(user): Add fields here
