apiVersion: v1
kind: Pod
metadata:
  name: jack
spec:
  containers:
    - name: ubuntu
#      image: ubuntu:latest
      image: alpine:latest
      # Just sleep forever
      command: [ "sleep" ]
      args: [ "infinity" ]